# Copyright (c) 2024, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: "WSO2 Integrator: BI Documentation"
site_description: "Documentation for WSO2 Integrator: BI"
site_author: WSO2
site_url: https://bi.docs.wso2.com/

# Repository information
repo_name: wso2/docs-ballerina-integrator
repo_url: https://github.com/anupama-pathirage/docs-bi-new
edit_uri: https://github.com/anupama-pathirage/docs-bi-new/edit/main/en/docs/
dev_addr: localhost:8000

# Copyright
copyright: "WSO2 Integrator: BI - Documentation"

# Configuration
theme:
  name: material
  custom_dir: theme/material
  logo: images/logo.svg
  favicon: images/bi-logo.svg
  features:
    # - content.code.copy
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - content.action.edit
    # - content.action.view
    # - navigation.indexes

    #- navigation.expand
    - navigation.path
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.action.view
  #highlightjs: true
  feature:
    tabs: true
  language: 'en'
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Strict Mode
strict: false # Set to true to break the build if there are warnings

# Navigation structure
nav:
  - Home: index.md
  - Get started:
      - Introduction: get-started/introduction.md
      - "Install WSO2 Integrator: BI": get-started/install-wso2-integrator-bi.md
      - Develop Automation: get-started/develop-automation.md
      - Develop AI Agent: get-started/develop-ai-agent.md
      - Develop Integration as API: get-started/develop-integration-as-api.md
      - Develop Event Integration: get-started/develop-event-integration.md
      - Develop File Integration: get-started/develop-file-integration.md
    #  - Key Concepts: get-started/key-concepts.md
  - Integration Guides:
      - Automation: 
        - integration-guides/automation/index.md
        - Periodic Data Synchronization: integration-guides/automation/periodic-data-synchronization.md
        - Extract Transform and Load (ETL): integration-guides/automation/extract-transform-load.md
      - Integration For AI:
        - integration-guides/integration-for-ai/index.md
        - AI Agent:
          - integration-guides/integration-for-ai/ai-agent/index.md
          - Introduction to Chat Agents: integration-guides/integration-for-ai/ai-agent/introduction-to-chat-agents.md
          - Introduction to Inline Agents: integration-guides/integration-for-ai/ai-agent/introduction-to-inline-agents.md
          - Integrating Agents with External Endpoints: integration-guides/integration-for-ai/ai-agent/integrating-agents-with-external-endpoints.md
        - RAG:
          - Build a RAG Application: integration-guides/integration-for-ai/rag/build-a-rag-application.md
        - Natural functions: integration-guides/integration-for-ai/natural-functions/natural-functions.md
      - Integration As API:
        - integration-guides/integration-as-api/index.md
        - HTTP Service:
          - Data Service: integration-guides/integration-as-api/http-service/data-service.md
          - Message Routing: integration-guides/integration-as-api/http-service/message-routing.md
          - Service Orchestration: integration-guides/integration-as-api/http-service/service-orchestration.md
        - GraphQL Service:
          - Expose Data with GraphQL: integration-guides/integration-as-api/graphql-service/expose-data-with-graphql.md
      - Event Integration:
        - integration-guides/event-integration/index.md
        - Event Integration With Kafka: integration-guides/event-integration/event-integration-with-kafka.md
        - Event Integration With RabbitMQ: integration-guides/event-integration/event-integration-with-rabbitmq.md
        - Change Data Capture: integration-guides/event-integration/change-data-capture.md
      - File Integration:
        - integration-guides/file-integration/index.md
        - File Integration With Directory Service: integration-guides/file-integration/file-integration-with-directory-service.md
        - File integration with FTP service: integration-guides/file-integration/file-integration-with-ftp-service.md
  - Developer Guides:
      - Project: developer-guides/integration-project.md
      - Artifacts: developer-guides/artifacts.md
      - Design the Integrations: developer-guides/design-the-integrations.md
      - Data Mapping: developer-guides/data-mapping.md
      - Protocols and Connectors:
        - Supported Protocols: developer-guides/protocols-and-connectors/supported-protocols.md
        - Connectors: developer-guides/protocols-and-connectors/connectors.md
        - Build a Local Connector: developer-guides/protocols-and-connectors/build-a-local-connector.md
      - AI for Integration:
        - developer-guides/ai-for-integration/index.md
        - WSO2 Copilot: developer-guides/ai-for-integration/wso2-copilot.md
        - AI Assisted Testing: developer-guides/ai-for-integration/ai-assisted-testing.md
        - AI Assisted Data Mapping: developer-guides/ai-for-integration/ai-assisted-data-mapping.md
      - Configure the Integration: developer-guides/configure-the-integration.md
      - Test the Integrations: developer-guides/test-the-integrations.md
      - Debug the Integrations: developer-guides/debug-the-integrations.md
      - Try the Integrations: developer-guides/try-the-integrations.md
  - Deployment:
      - deployment/index.md
      - Deploy to Devant: deployment/deploy-to-devant.md
      - VM Based Deployment:
        - deployment/vm-based-deployment/index.md
        - Centralized Deployment: deployment/vm-based-deployment/centralized-deployment.md
        - Decentralized Deployment: deployment/vm-based-deployment/decentralized-deployment.md
      - Containerized Deployment:
        - deployment/containerized-deployment/index.md
        - Deploy as Docker Image: deployment/containerized-deployment/deploy-as-docker-image.md
        - Deploy on Kubernetes: deployment/containerized-deployment/deploy-on-kubernetes.md
  - Observability and Monitoring:
      - "Monitoring with WSO2 Integrator: ICP": observability-and-monitoring/monitoring-with-wso2-integrator-icp.md
      - Observability with Devant: observability-and-monitoring/observability-with-devant.md
      - Supported Tools and Platforms: observability-and-monitoring/supported-tools-and-platforms.md
  - Migration Tools:
        - Mulesoft Migration Tool: migration-tools/mulesoft-migration-tool.md
        - TIBCO BusinessWorks Migration Tool: migration-tools/tibco-businessworks-migration-tool.md
        - Logic Apps Migration Tool: migration-tools/logic-apps-migration-tool.md
  - References:
      - Enterprise Integration Patterns: references/enterprise-integrations-patterns.md
# Markdown extensions configuration
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - markdown_include.include:
      base_path: docs
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: docs
  - attr_list

# Plugins configuration
plugins:
  - search
  - markdownextradata: {}
  - exclude:
      glob:
        - wip/*
  - redirects:
      redirect_maps:

# Extra configuration
extra_css:
  # You can select a different theme for syntax highlighting by simply
  # selecting a different css file below from the available list.
  - assets/lib/highlightjs/styles/vs.min.css
  # Make sure to activate only one palette at a time.
  # If all the palettes are commented out, the default material theme palette will take over
  - assets/css/blue-palette-alt1.css
  # - assets/css/blue-palette-alt2.css
  # - assets/css/blue-palette.css
  # - assets/css/green-palette.css
  # - assets/css/orange-palette.css
  - assets/css/mitheme.css
  - assets/css/custom.css
  - assets/lib/json-formatter/json-formatter.css
  - assets/css/config-catalog.css
  - assets/lib/fontawesome-free-6.3.0-web/css/all.min.css
#  - assets/css/redoc.css
extra_javascript:
  - assets/lib/highlightjs/highlight.min.js
  - assets/lib/json-formatter/json-formatter.umd.js
  - assets/js/mitheme.js
  # - assets/lib/backtotop/js/util.js
  # - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
  # site_version: Uncomment to specify a version
  #base_path: https://anupama-pathirage.github.io/docs-bi-new/
  base_path: http://localhost:8000
